### ISSUE TITLE
Update InlineInput to allow undefined `value` prop

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana-aws-sdk-react#15]
## Description
Currently, the InlineInput has a compulsory prop `value` that is a string. 
If we want to render an input that has no value, we have to send it an empty string. It would be best to have the option to pass `undefined` or no `value` at all

## Code

https://github.com/grafana/grafana-aws-sdk-react/blob/1d744d0937499a0a89809df89d820c0046af2cfa/src/sql/ConfigEditor/InlineInput.tsx#L7-L16

## Acceptance criteria:

- [ ] The following code can be ran even if `clusterIdentifier` does not exist:
```
<InlineInput
        {...props}
        value={props.options.jsonData.clusterIdentifier}
/>
```

**Comment by fridgepoet** [comment]
We've decided not to work on this one for now.
